version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kirk958617
      MYSQL_DATABASE: db_test
    volumes:
      - data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
  
volumes:
  data:
    driver: local
